language: php
matrix:
    fast_finish: true
    include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
      env: COVERAGE=yes

services:
  - mongodb

env:
  global:
    - PECLSOLR=solr-2.4.0

before_install:
  - sudo apt-get update > /dev/null
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
  - pecl channel-update pecl.php.net

install:
  # install Mongo extension
  - 'if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.2" ]]; then
      pecl install mongodb;
    fi'
  # install SOLR extension
  # using solr master version in php 7.2
  - 'if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then
      export HASH=de1d724299780d927cb9ed14268449ac8a28204b;
      curl --location https://github.com/php/pecl-search_engine-solr/archive/${HASH}.tar.gz -o solr.tgz;
      sh -c "tar xfz solr.tgz";
      sh -c "cd pecl-search_engine-solr-${HASH} && phpize && ./configure && make && sudo make install";
    else
      sh -c "wget http://pecl.php.net/get/$PECLSOLR.tgz";
      sh -c "tar xfz $PECLSOLR.tgz";
      sh -c "cd $PECLSOLR && phpize && ./configure && make && sudo make install";
    fi'
  - phpenv config-add etc/travis/phpenv.ini
  - COMPOSER_MEMORY_LIMIT=-1 composer install

script:
  - 'if [[ $COVERAGE = yes ]]; then
        ./vendor/bin/phpunit --verbose --coverage-clover=build/logs/clover.xml --coverage-php=build/logs/clover.serialized;
    else
        ./vendor/bin/phpunit --verbose;
    fi'

after_script:
  # process coverage
  - 'if [[ $COVERAGE = yes ]]; then
        composer require php-coveralls/php-coveralls --no-scripts;
        ./vendor/bin/php-coveralls -vvv;
        wget https://scrutinizer-ci.com/ocular.phar;
        ocular.phar code-coverage:upload --format=php-clover build/logs/clover.serialized;
    fi'