language: php

cache:
    directories:
    - "$HOME/.composer/cache"
    - "$HOME/.npm"

matrix:
    fast_finish: true
    include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.1'
      env: COVERAGE=yes

services:
  - mongodb

before_install:
  - sudo apt-get update > /dev/null
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"

install:
  # install php packages required for running YAWIK phpunit tests
  - sudo apt-get install -y --force-yes php5-intl php5-curl php5-xsl

  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  # install Mongo extension
  - pecl install mongodb

  # install SOLR extension
  - pecl install solr

  - phpenv config-add etc/travis/phpenv.ini
  - composer install

script:
  - 'if [[ $COVERAGE = yes ]]; then
        ./vendor/bin/phpunit --verbose --coverage-clover=build/logs/clover.xml --coverage-php=build/logs/clover.serialized;
    else
        ./vendor/bin/phpunit --verbose;
    fi'

after_script:
  - 'if [[ $COVERAGE = yes ]]; then
        composer require php-coveralls/php-coveralls;
        travis_retry ./vendor/bin/php-coveralls -vvv;
        wget https://scrutinizer-ci.com/ocular.phar;
        travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.serialized;
    fi'