language: php
php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.1"
    env: COVERAGE=yes

services:
  - mongodb

env:
  - PECLMONGO=mongo-1.6.10 PECLSOLR=solr-2.4.0

before_install:
  - sudo apt-get update > /dev/null
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"

install:
  # install php packages required for running YAWIK phpunit tests
  - sudo apt-get install -y --force-yes php5-intl php5-curl php5-xsl

  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  # install Mongo extension
  - sh -c "wget http://pecl.php.net/get/$PECLMONGO.tgz"
  - sh -c "tar xfz $PECLMONGO.tgz"
  - sh -c "cd $PECLMONGO && phpize && ./configure && make && sudo make install"

  # install SOLR extension
  - sh -c "wget http://pecl.php.net/get/$PECLSOLR.tgz"
  - sh -c "tar xfz $PECLSOLR.tgz"
  - sh -c "cd $PECLSOLR && phpize && ./configure && make && sudo make install"

  - phpenv config-add etc/travis/phpenv.ini
  - composer install

script:
  - 'if [[ $COVERAGE = yes ]]; then
        ./vendor/bin/phpunit --verbose --coverage-clover=build/logs/clover.xml --coverage-php=build/logs/clover.serialized;
    else
        ./vendor/bin/phpunit --verbose;
    fi'

after_script:
  - cd `dirname $TRAVIS_BUILD_DIR`/yawik/module/Solr
  - php `dirname $TRAVIS_BUILD_DIR`/yawik/vendor/bin/coveralls -vvv
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.serialized