language: php

cache:
    directories:
    - "$HOME/.composer/cache"
    - "$HOME/.npm"

matrix:
    fast_finish: true
    include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.1'
      env: COVERAGE=yes

services:
  - mongodb

before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install libcurl4-gnutls-dev libxml2-dev
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"

install:
  - pecl channel-update pecl.php.net

  # install Mongo extension
  - pecl install mongodb

  # install SOLR extension
  - sh -c "wget http://pecl.php.net/get/solr-2.4.0.tgz"
  - sh -c "tar xfz $PECLSOLR.tgz"
  - sh -c "cd $PECLSOLR && phpize && ./configure && make && sudo make install"

  - phpenv config-add etc/travis/phpenv.ini
  - composer install

script:
  - 'if [[ $COVERAGE = yes ]]; then
        ./vendor/bin/phpunit --verbose --coverage-clover=build/logs/clover.xml --coverage-php=build/logs/clover.serialized;
    else
        ./vendor/bin/phpunit --verbose;
    fi'

after_script:
  - 'if [[ $COVERAGE = yes ]]; then
        composer require php-coveralls/php-coveralls;
        travis_retry ./vendor/bin/php-coveralls -vvv;
        wget https://scrutinizer-ci.com/ocular.phar;
        travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.serialized;
    fi'