version: "3"
services:
    nginx:
        image: nginx:alpine
        container_name: yawik.solr.nginx
        volumes:
            - ./etc/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/yawik
        ports:
            - "80:80"
        links:
            - php
            - mongo
        environment:
            - UMASK=0
    php:
        container_name: yawik.solr.php
        build:
            context: ./etc/docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./etc/docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            - ./:/var/www/yawik
            - ./test/sandbox/var/docker/logs:/var/www/yawik/test/sandbox/var/log
            - ./test/sandbox/var/docker/cache:/var/www/yawik/test/sandbox/var/cache

    solr:
        container_name: yawik.solr
        build:
            context: ./etc/docker/solr
        ports:
            - "8983:8983"
        volumes:
          - ./contrib/conf:/opt/solr/server/solr/YawikJobs/conf

    mongo:
        image: mongo:3.4.10
        container_name: yawik.mongo
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./etc/docker/mongodb/data:/data/db
        ports:
            - "27017:27017"
        command: mongod --smallfiles --logpath=/dev/null # --quiet
